version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db-sga
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password_sga
      MYSQL_DATABASE: sga_challange
      MYSQL_USER: user_sga
      MYSQL_PASSWORD: password_sga
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sga
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-sga
    ports:
      - '3333:3333'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=user_sga
      - DB_PASSWORD=password_sga
      - DB_NAME=sga_challange
      - JWT_SECRET=ODJASBNDHASFVOWVPWQBEQWBENWQENWQJKENQW
    networks:
      - sga
    depends_on:
      - db
    command: >
      sh -c 'yarn build && yarn start:prod'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-sga
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://backend-sga:3333
    networks:
      - sga
    depends_on:
      - backend

networks:
  sga:
    driver: bridge

volumes:
  db_data:
